// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cor_cov_blockwise
NumericMatrix cor_cov_blockwise(NumericMatrix mat, NumericVector means, NumericVector vars, NumericVector sds, int c_ini, int c_end);
RcppExport SEXP mood_cor_cov_blockwise(SEXP matSEXP, SEXP meansSEXP, SEXP varsSEXP, SEXP sdsSEXP, SEXP c_iniSEXP, SEXP c_endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type means(meansSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vars(varsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sds(sdsSEXP);
    Rcpp::traits::input_parameter< int >::type c_ini(c_iniSEXP);
    Rcpp::traits::input_parameter< int >::type c_end(c_endSEXP);
    rcpp_result_gen = Rcpp::wrap(cor_cov_blockwise(mat, means, vars, sds, c_ini, c_end));
    return rcpp_result_gen;
END_RCPP
}
